version: "3.8"

services:
  web:
    build: .
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:80"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
