"""add_buss_photo_filename

Revision ID: 014da2ba4ce5
Revises: 5b28af7fa5f4
Create Date: 2023-07-24 12:35:09.634391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "014da2ba4ce5"
down_revision = "5b28af7fa5f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("busses", sa.Column("photo_filename", sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("busses", "photo_filename")
    # ### end Alembic commands ###
