"""add_bus_model

Revision ID: 20c01e7aeec8
Revises: 
Create Date: 2023-07-20 21:21:55.144025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20c01e7aeec8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("number_plate", sa.String(length=8), nullable=False),
        sa.Column("seats_quantity", sa.Integer(), nullable=False),
        sa.Column("color", sa.Enum("RED", "GREEN", "BLUE", name="color"), nullable=False),
        sa.CheckConstraint("seats_quantity >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number_plate"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bus")
    # ### end Alembic commands ###
