"""add_orders

Revision ID: 6dbf42a4309f
Revises: 3687c8693f05
Create Date: 2023-07-18 10:38:55.137704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6dbf42a4309f"
down_revision = "3687c8693f05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "PAYED", "FAILED", name="orderstatus"), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "passengers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("ticket_price", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passengers")
    op.drop_table("orders")
    # ### end Alembic commands ###
