"""add_city_model

Revision ID: b685dacd8d84
Revises: 20c01e7aeec8
Create Date: 2023-07-21 04:28:44.258312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b685dacd8d84"
down_revision = "20c01e7aeec8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city")
    # ### end Alembic commands ###
